### ISSUE TITLE
Not compatible with mongo driver 1.8.0

### ISSUE THREAD

**Issue by fbjork** [tomafro/mongo-rails-instrumentation#5]
``` ruby
/Users/fredrik/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method': undefined method `send_message_with_safe_check' for class `Mongo::Connection' (NameError)
    from /Users/fredrik/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method_chain'
    from /Users/fredrik/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/mongo-rails-instrumentation-0.2.4/lib/mongo/rails/instrumentation/railtie.rb:29:in `block (2 levels) in instrument'
    from /Users/fredrik/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/mongo-rails-instrumentation-0.2.4/lib/mongo/rails/instrumentation/railtie.rb:21:in `each'
    from /Users/fredrik/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/mongo-rails-instrumentation-0.2.4/lib/mongo/rails/instrumentation/railtie.rb:21:in `block in instrument'
    from /Users/fredrik/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/mongo-rails-instrumentation-0.2.4/lib/mongo/rails/instrumentation/railtie.rb:20:in `module_eval'
    from /Users/fredrik/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/mongo-rails-instrumentation-0.2.4/lib/mongo/rails/instrumentation/railtie.rb:20:in `instrument'
    from /Users/fredrik/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/mongo-rails-instrumentation-0.2.4/lib/mongo/rails/instrumentation/railtie.rb:6:in `block in <class:Railtie>'
    from /Users/fredrik/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/railties-3.2.9/lib/rails/initializable.rb:30:in `instance_exec'
    from /Users/fredrik/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/railties-3.2.9/lib/rails/initializable.rb:30:in `run'
    from /Users/fredrik/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/railties-3.2.9/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /Users/fredrik/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/railties-3.2.9/lib/rails/initializable.rb:54:in `each'
    from /Users/fredrik/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/railties-3.2.9/lib/rails/initializable.rb:54:in `run_initializers'
    from /Users/fredrik/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/railties-3.2.9/lib/rails/application.rb:136:in `initialize!'
    from /Users/fredrik/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/railties-3.2.9/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /Users/fredrik/Projects/Banjo/banjo-api/config/environment.rb:5:in `<top (required)>'
    from /Users/fredrik/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:251:in `require'
    from /Users/fredrik/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:251:in `block in require'
    from /Users/fredrik/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /Users/fredrik/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:251:in `require'
    from /Users/fredrik/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/railties-3.2.9/lib/rails/application.rb:103:in `require_environment!'
    from /Users/fredrik/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/railties-3.2.9/lib/rails/commands.rb:40:in `<top (required)>'
    from script/rails:11:in `require'
    from script/rails:11:in `<main>'
```

**Comment by manuelmeurer** [comment]
Getting the same error.

**Comment by tomafro** [comment]
The latest version `0.3.0` should have fixed this.  Sorry for not sorting it out sooner.

**Comment by manuelmeurer** [comment]
Thanks!
